---
title: "CALPM"
author: "Grupa 2"
format: 
  html:
    toc: true
    toc-location: right
    toc-title: Spis Treści
    number-sections: true
    embed-resources: true
    html-math-method: katex
    code-tools: true
    code-fold: show
    code-summary: "Show and hide code"
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    self-contained: true
    fig-align: center
execute: 
  echo: true
  error: false
  warning: false
  output: true
---

# Dane
```{r}
library(tidyverse)
library(openair)
```

```{r}
load("dane/ops.RData") 
```

```{r}
ops |> summary()
ops |> is.na() |> colSums()
ops |> glimpse()
```


```{r}
load("dane/ops.RData") ; ops <- ops |> na.omit()
load("dane/data_test.rdata")
```

```{r}
weryfikacja <- ops_data |> select(date:prec)
weryfikacja <- weryfikacja |> 
  left_join(bam, by = "date") |> 
  mutate(grimm_pm10 = bam_pm10) |> 
  select(-bam_pm10)
ops <- ops |> select(-ops_pm10, -pres_sea)

nazwy <- colnames(ops) |> dput()
weryfikacja <- weryfikacja |> 
  select(all_of(nazwy))

colnames(weryfikacja) == colnames(ops)
```
